### PR TITLE
keywords: encode xattr.* keywords with Vis

### LINKED ISSUE #109: [BUG] xattr: spaces in extended attribute keys fail
If you install `python3-xattrs`, you can check this pretty easily:

```
% mkdir dir
% touch dir/a
% xattr -w user."some key" "some value" dir/a
% gomtree -c -p dir/ > mtree
% gomtree -f mtree -p dir/
2016/12/18 03:00:43 Unknown keyword "" for file "dir"
```

Which happens because the space is not encoded with `Vis`.

@vbatts We really should do a pass and make sure that **everything** is encoded properly. Because we've had this issue quite a few times.

### PR DESCRIPTION
**Pull request by cyphar**
This allows for xattr keywords to include spaces and other such options
(which is perfectly valid according to the definition of Lsetxattr --
any character except '\x00' is fair game).

Fixes #109
Signed-off-by: Aleksa Sarai <asarai@suse.de>

### CODE REVIEW

**Comment by vbatts** [comment]
nice catch. Can we add a test for this?

**Comment by vbatts** [comment]
something like
```bash
#!/bin/bash
set -e

name=$(basename $0)
root="$(dirname $(dirname $(dirname $0)))"
gomtree=$(readlink -f ${root}/gomtree)
t=$(mktemp -d ${root}/go-mtree.XXXXXX)

echo "[${name}] Running in ${t}"

touch "${t}/file"

setfattr -n user.testing -v apples "${t}/file"
$gomtree -c -k "sha256digest,xattrs" -p ${t} > /tmp/t.mtree

setfattr -n user.testing -v bananas "${t}/file"
$gomtree -p ${t} -f /tmp/t.mtree && echo "xattr change did not cause a failure"

rm -fr ${t}
```
... except that while it reports that the xattr has changed, `gomtree` returns 0 so the something is not right.

**Comment by cyphar** [comment]
@vbatts it looks like you disabled the `len(res)` checking for missing keywords in 21723a3974bc47e3950708caf5cfdf4a65086efc. Fixing it would be a bit of a pain IMO if we want to handle FreeBSD.

**Comment by cyphar** [comment]
@vbatts I've re-enabled `gomtree`'s erroring out code (only if `Modified` is set for at least one entry). I think we should add a `--strict` flag to check all of the manifest entries properly -- we've being too lenient in certain cases IMO.

File: test/cli/0003.sh [hunk 1]
```diff
@@ -0,0 +1,33 @@
+#!/bin/bash
+set -e
+
+name=$(basename $0)
+root="$(dirname $(dirname $(dirname $0)))"
+gomtree=$(readlink -f ${root}/gomtree)
+t=$(mktemp -d ${root}/go-mtree.XXXXXX)
```
Comment (vbatts) [inline test/cli/0003.sh]: the reason i put this as making a temp directory in `${root}` in my example was because some `$TMPDIR` are mounted without xattr support. kind of a silly assumption.

**Comment by vbatts** [comment]
locally this 0003.sh fails
```
[0003.sh] Running in ./go-mtree.fEZN1D
"file": keyword "xattr": expected YXBwbGVzIGFuZCBiYW5hbmFz; got dW5jb25maW5lZF91Om9iamVjdF9yOnVzZXJfaG9tZV90OnMwAA== xattr.user.mtree.testing=YmFuYW5hcyBhbmQgbGVtb25z
2017/01/14 09:55:22 mainfest validation failed
"file": keyword "xattr": expected YXBwbGVzIGFuZCBiYW5hbmFz; got dW5jb25maW5lZF91Om9iamVjdF9yOnVzZXJfaG9tZV90OnMwAA==
2017/01/14 09:55:22 mainfest validation failed
"file": keyword "xattr": expected YXBwbGVzIGFuZCBiYW5hbmFz; got dW5jb25maW5lZF91Om9iamVjdF9yOnVzZXJfaG9tZV90OnMwAA== xattr.user.mtree.another=YW5vdGhlciAgYT1i xattr.user.mtree.testing=YXBwbGVzIGFuZCBiYW5hbmFz
2017/01/14 09:55:22 mainfest validation failed
"file": keyword "xattr": expected YXBwbGVzIGFuZCBiYW5hbmFz; got dW5jb25maW5lZF91Om9iamVjdF9yOnVzZXJfaG9tZV90OnMwAA== xattr.user.mtree.testing=YXBwbGVzIGFuZCBiYW5hbmFz
2017/01/14 09:55:22 mainfest validation failed
FAILED: ./test/cli/0003.sh
```

File: test/cli/0003.sh (hunk 1 above)
Comment (cyphar) [inline test/cli/0003.sh]: I'll switch it to `$TMPDIR`. We will automatically skip this test if `xattrs` don't work (line 9).

**Comment by cyphar** [comment]
@vbatts It's because you use SELinux :wink:. Can you get the `mtree` manifest and paste it here?

```
% echo dW5jb25maW5lZF91Om9iamVjdF9yOnVzZXJfaG9tZV90OnMwAA== | base64 -d
unconfined_u:object_r:user_home_t:s0
```

**Comment by vbatts** [comment]
haha. That's humorous. I usually test on my desktop that is not using selinux, but this time was testing from an f25 box. :-D
```
#          user: vbatts
#       machine: valse.usersys.redhat.com
#          tree: go-mtree.fEZN1D/dir
#          date: Sat Jan 14 09:55:22 2017
#      keywords: type,sha256digest,xattr

# .
/set type=file uid=1000 gid=1000
. type=dir xattr.security.selinux=dW5jb25maW5lZF91Om9iamVjdF9yOnVzZXJfaG9tZV90OnMwAA==
    file sha256digest=e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 xattr.security.selinux=dW5jb25maW5lZF91Om9iamVjdF9yOnVzZXJfaG9tZV90OnMwAA== xattr.user.mtree.testing=YXBwbGVzIGFuZCBiYW5hbmFz
..
```

**Comment by vbatts** [comment]
LGTM
we can chase down the selinux issue separately
